Bunks/urls.py
from django.urls import path

from . import views
app_name = "Bunks"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:from_user>', views.user, name='user'),
    path('new', views.new, name='new')
]

jitterbug/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bunks/', include('Bunks.urls')),
]

Bunks/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=200)
    photo = models.CharField(max_length=200)

class Bunk(models.Model):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    time = models.DateTimeField('Date:')

Bunks/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import User, Bunk
from django.template import loader
from django.urls import reverse
from django.utils import timezone

# Create your views here.
def index(request):
    bunks = Bunk.objects.order_by("-time")
    template = loader.get_template('Bunks/index.html')
    context = {
        "list_of_bunks": bunks
    }
    return HttpResponse(template.render(context, request))

def user(request, from_user):
    sent_bunks = Bunk.objects.filter(from_user = from_user)
    received_bunks = Bunk.objects.filter(to_user = from_user)
    template = loader.get_template('Bunks/user.html')
    user = User.objects.get(pk=from_user)
    context = {
        "user": user,
        "sent": sent_bunks,
        "received": received_bunks,
    }
    return HttpResponse(template.render(context, request))

def new(request):
    
    if request.method == 'POST':
        sender = User.objects.get(pk=request.POST['sender'])
        receiver = User.objects.get(pk=request.POST['receiver'])
        bunk = Bunk()
        bunk.from_user = sender
        bunk.to_user = receiver
        bunk.time = timezone.now()
        bunk.save()
        return HttpResponseRedirect(reverse('Bunks:index'))
    else:
        template = loader.get_template('Bunks/new.html')
        context = {
            "users": User.objects.all()
        }
        return HttpResponse(template.render(context, request))

Bunks/templates/Bunks/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Bunks/style.css' %}">
{% if list_of_bunks %}
    <ul>
    {% for bunk in list_of_bunks %}
        <li><a href="{% url 'Bunks:user' bunk.from_user.id %}">{{bunk.from_user.username}}</a> Bunked <a href="{% url 'Bunks:user' bunk.to_user.id %}">{{bunk.to_user.username}}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No bunks (sad face)</p>
{% endif %}

<a href="{% url 'Bunks:new'%}">Bunk someone</a>
    

Bunks/templates/Bunks/new.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Bunks/style.css' %}">
<form action="{% url 'Bunks:new' %}" method="post">
    {% csrf_token %}
    <label for="sender">who are you?</label>
    <select name="sender">
        {% for u in users%}
            <option value={{u.id}}>{{u.username}}</option>
        {% endfor %}
    </select>
    <br>
    <label for="receiver">who is this for?</label>
    <select name="receiver">
        {% for u in users%}
            <option value={{u.id}}>{{u.username}}</option>
        {% endfor %}
    </select>
    <br>
    <input type="submit" value="Submit">
</form>

Bunks/templates/Bunks/user.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'Bunks/style.css' %}">
<h1>{{user.username}}</h1>
<p>This user has bunked</p>
<ul>
    {%for s in sent%}
        <li><a href="{% url 'Bunks:user' s.to_user.id %}">{{s.to_user.username}}</a></li>
    {%endfor%}
</ul>

<p>this user has been bunked by</p>
<ul>
    {%for r in received%}
        <li><a href="{% url 'Bunks:user' r.from_user.id %}">{{r.from_user.username}}</a></li>
    {%endfor%}
</ul>